@extends('layouts.marketing')
@section('title', 'Privacy Policy — NexPill')
@section('description', 'How NexPill collects, uses, protects, and lets you control medication-related data.')
@section('content')
<section class="legal-hero"><div class="shell narrow"><div class="eyebrow"><span></span>Legal & privacy</div><h1>Privacy, in plain language.</h1><p>Effective 29 August 2026 · Version 1.0</p></div></section>
<section class="legal-body"><div class="shell legal-grid"><aside><a href="#summary">Summary</a><a href="#collect">What we collect</a><a href="#use">How we use it</a><a href="#sharing">Sharing</a><a href="#rights">Your choices</a><a href="#security">Security</a><a href="#contact">Contact</a></aside><article class="prose">
<h2 id="summary">The short version</h2><p>NexPill stores account details and the health information you choose to enter so it can provide reminders, adherence history, refill tracking, appointments and family-care features. We do not sell personal or health data.</p><div class="legal-callout"><strong>Important:</strong> NexPill is a medication organization tool, not a medical provider, emergency service or substitute for professional advice.</div>
<h2 id="collect">Information we collect</h2><h3>Account and device data</h3><p>Name, email, optional phone number, timezone, language, device identifiers, app version and push-notification token.</p><h3>Health and care data you provide</h3><p>Medicine names, dose instructions, schedules, dose history, refill quantities, side effects, appointment details, uploaded prescriptions and family-care relationships.</p><h3>Service and security data</h3><p>IP address, user agent, authentication records, support conversations, audit events and diagnostic logs needed to keep the service reliable and secure.</p>
<h2 id="use">How we use information</h2><ul><li>Deliver reminders and show your medication plan.</li><li>Calculate adherence and create reports you request.</li><li>Enable role-based family access and managed dependents.</li><li>Respond to support, prevent abuse and improve reliability.</li><li>Meet legal obligations and enforce our terms.</li></ul>
<h2 id="sharing">When information is shared</h2><p>Information is shared with family members only after an invitation is accepted or a managed dependent is created. We may use infrastructure, email, notification, storage and analytics processors under contracts that limit their use of data. We may disclose information when legally required or to protect users from serious harm.</p>
<h2 id="rights">Your choices and controls</h2><p>You can update notification preferences, revoke family access, export your data, sign out devices and request account deletion. Some records may be retained where required for security, fraud prevention or law. To exercise a privacy right, use the in-app controls or the data-deletion page.</p>
<h2 id="security">Security and retention</h2><p>We use encrypted transport, hashed credentials and one-time codes, token-based access, role checks, least-privilege administration, backups and audit logs. No system is perfectly secure. Keep your device protected and contact us promptly if you suspect unauthorized access.</p>
<h2>Children and managed profiles</h2><p>A parent, guardian or authorized caregiver must create and control a managed profile for a child or person who cannot manage their own account. Do not enter information unless you are authorized to do so.</p>
<h2>International processing and changes</h2><p>Service providers may process data in other regions with appropriate safeguards. If this policy changes materially, we will update the effective date and provide notice where required.</p>
<h2 id="contact">Contact</h2><p>Privacy questions: <a href="mailto:privacy@nexpill.app">privacy@nexpill.app</a>. Before production launch, the operating legal entity, registered address, jurisdiction-specific rights and grievance officer details must be inserted here.</p>
</article></div></section>
@endsection
